### ISSUE TITLE
Force Generators cause weird stuff

### ISSUE THREAD

**Issue by DelfKah** [rgerum/ElViS#11]
Oftentimes I can't run the simulation when I have added a force generator. Also, I can only add force generators in the last two examples.

**Comment by rgerum** [comment]
Well, when the system cannot be solved, ElViS cannot display a solution. But at least it can now display a proper error message and still displays the system.

**Comment by DelfKah** [comment]
Ok, how about a force generator and a spring in parallel. Shouldn't that work?

**Comment by rgerum** [comment]
Should only work if the last point it fixed (e.g. external displacement setting). If not, the point right of the force generator can be pulled to an arbitrary position.
