### ISSUE TITLE
Option for fixed points

### ISSUE THREAD

**Issue by DelfKah** [rgerum/ElViS#12]
Give the option to make a node fixed (or free).

Maybe it would be practical to only allow the outermost nodes to be fixed and to only allow force generators when both outermost nodes are already fixed. I guess that would save us a lot of trouble, right? I guess there is no biophysical application for a force generator with a free end (?)

**Comment by rgerum** [comment]
well, if you want to give a muscle a pre stress, it is an application for a force generator with an external force.
